---
title: "Who is the Greatest?"
authors: "Matthew Grosshans and Aman Arora"
date: December 17, 2019
output: html_notebook
---

### Research Question
Who was the better player off the 2000s era, according to statistics?

### Packages

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaic)
library(tidyverse)
library(DataComputing)
library(rvest)
library(lubridate)
library(dplyr)
```

### Data Access
```{r}
page <- "https://www.basketball-reference.com/players/b/bryanko01.html"
tableList <- page %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
KobeBryant <- tableList[[1]]
KobeBryant
```
```{r}
page <- "https://www.basketball-reference.com/players/j/jamesle01.html"
tableList <- page %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
LebronJames <- tableList[[1]]
LebronJames
```


### Joining the Data Tables Together
```{r}
AllPlayers <-
  left_join(KobeBryant, LebronJames, by='Age') 
AllPlayers                


# used left join to combine all 2 data tables together
```


### General Data Wrangling
```{r}
AllPlayers%>%
  select(`Age`,`3P.x`,`2P.x`,`AST.x`,`3P.y`,`2P.y`,`AST.y`)
```


### Regular Expression
```{r}
AllPlayers %>% 
  filter(grepl("19", Age, ignore.case = TRUE)) 
```
### Reduction/Transformation Function
```{r}
AllPlayers %>% 
  summarise(KobePoints = mean(PTS.x, na.rm = TRUE), 
            LebronPoints = mean(PTS.y, na.rm = TRUE))
```
### 
```{r}
PlayersMachine <- 
  party::ctree(Age == "28" ~ PTS.x + PTS.y, data=AllPlayers)
```

### Data Visualization 1

```{r}




```

### Data Visualization 2
```{r}



```





### Data Visualization 3

```{r}



```


